apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiz-admission-controller.fullname" . }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "wiz-admission-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wiz-admission-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wiz-admission-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 8443
          volumeMounts:
          - mountPath: /var/server-certs
            name: server-certs
            readOnly: true
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /live
              port: 8000
              scheme: HTTPS
          command:
          - "/usr/bin/wiz-admission-controller-server"
          - "--port=8443"
          - "--tls-private-key-file=/var/server-certs/tls.key"
          - "--tls-cert-file=/var/server-certs/tls.crt"
          - "--error-enforcement-method=BLOCK"
          - "--policy=bar-ac-fw"
          env:
          - name: WIZ_ADMISSION_CONTROLLER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-admission-controller.secretApiToken" . }}
                key: clientId
                optional: false
          - name: WIZ_ADMISSION_CONTROLLER_CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-admission-controller.secretApiToken" . }}
                key: clientToken
                optional: false
          - name: WIZ_ADMISSION_CONTROLLER_ENV
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-admission-controller.secretApiToken" . }}
                key: clientEnv
                optional: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: server-certs
          secret:
            defaultMode: 400
            secretName: {{ include "wiz-admission-controller.fullname" . }}-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
