apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-admission-controller.secretApiToken" . }}
data:
  clientId: {{ required "Missing required value wizApiToken.clientId is required" .Values.wizApiToken.clientId | b64enc | quote }}
  clientToken: {{ required "Missing required value: wizApiToken.clientToken is required" .Values.wizApiToken.clientToken | b64enc | quote }}
  clientEnv: {{ required "Missing required value: wizApiToken.env is required" .Values.wizApiToken.env | b64enc | quote }}
