# Default values for wiz-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "wiz-broker"
namespace: "kube-system"

brokerServiceAccount: 
  # Annotations to add to the broker service account
  annotations: {}
  # The name of broker service account to use
  name: "wiz-broker"

installRbac: false
installBroker: false

serviceAccount:
  # Annotations to add to the connector service account
  annotations: {}
  # The name of the connector service account to use.
  name: "wiz-kube-connector"

image:
  repository: wizsec/tunnel-client
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

replicaCount: 1

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false

# required arguments
wizConnector:
  connectorId: ""
  connectorToken: ""
  targetDomain: ""
  targetIp: ""
  targetPort: ""
  tunnelServerAddress: ""
  tunnelServerPort: ""
  httpProxy: ""

# optional arguments
secretName:
